#!/bin/bash
#Script to prepare for Codeforces Round
echo "Creating Directory..."
mkdir -p /home/vazzup/CodeForces/Round\ $1
echo "Directory Created..."
echo "Moving to directory..."
cd /home/vazzup/CodeForces/Round\ $1
echo "Creating Files..."
cp ../Makefile Makefile
cp ../template.cpp A.cpp
cp ../template.cpp B.cpp
cp ../template.cpp C.cpp
cp ../template.cpp D.cpp
cp ../template.cpp E.cpp
chmod 700 A.cpp
chmod 700 B.cpp
chmod 700 C.cpp
chmod 700 D.cpp
chmod 700 E.cpp
echo "Files Created..."
echo "Opening A.cpp in vi..."
vi A.cpp
