#!/bin/bash
#Script to prepare for Codeforces Round
echo "Creating Directory..."
mkdir -p /home/vazzup/CodeForces/Round\ $1
echo "Directory Created..."
echo "Moving to directory..."
cd /home/vazzup/CodeForces/Round\ $1
echo "Creating Files..."
cp ../template.cpp A.cpp
cp ../template.cpp B.cpp
cp ../template.cpp C.cpp
cp ../template.cpp D.cpp
cp ../template.cpp E.cpp
sudo chmod 700 A.cpp
sudo chmod 700 B.cpp
sudo chmod 700 C.cpp
sudo chmod 700 D.cpp
sudo chmod 700 E.cpp
echo "Files Created..."
echo "Opening A.cpp in vi..."
vi A.cpp
