#!/bin/bash
DIR=$1
echo $DIR
COUNT=`sqlite3 ~/.dirdb.db "SELECT count(dirID) FROM Directories WHERE dirName IS '$DIR'"`;
LIST=`sqlite3 ~/.dirdb.db "SELECT dirID, dirPath FROM Directories WHERE dirName IS '$DIR'"`;
#echo $LIST
#echo $COUNT
if [ $COUNT = "1" ]; then
	for ROW in $LIST; do
		MYPATH=`echo "$ROW" | awk '{split($0,a,"|"); print a[2]}'`
		echo $MYPATH
	done
else
	for ROW in $LIST; do
		MYID=`echo $ROW | awk '{split($0,a,"|"); print a[1]}'`
		MYPATH=`echo $ROW | awk '{split($0,a,"|"); print a[2]}'`
		echo $MYID" "$MYPATH
	done
	read MYID
	for ROW in $LIST; do
		CURRID=`echo $ROW | awk '{split($0,a,"|"); print a[1]}'`
		if [ $CURRID = $MYID ]; then
			MYPATH=`echo $ROW | awk '{split($0,a,"|"); print a[2]}'`
		fi
	done
fi
echo $MYPATH
gnome-terminal --working-directory=$MYPATH
