#!/usr/bin/env bash

kill=1
DIR=

while [ "$1" != "" ]; do
	case $1 in
		-dk | --dont-kill )	kill=0
							;;
		* )					DIR="$1"
							;;
	esac
	shift
done

goto.py "$DIR"

if [ "$kill" = "1" ]; then
	kill -9 $PPID
fi
